old_site/app/models.py
from app import db
import os

class User(db.Model):
    id       = db.Column(db.Integer, primary_key=True, index=True)
    username = db.Column(db.String(), index=True, unique=True)
    email    = db.Column(db.String(), index=True, unique=True)
    password = db.Column(db.String())
    

old_site/app/__init__.py
import os
from flask import Flask, request
from config import Config
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager

db      = SQLAlchemy()
migrate = Migrate()
login   = LoginManager()

def start_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)

    db.init_app(db);

    # Register the blueprint modules
    from app.website import website
    from app.users import users
    from app.api import api

    app.register_blueprint(website)
    app.register_blueprint(users, url_prefix="/users")
    app.register_blueprint(api, url_prefix="/api")

    return app

old_site/app/admins/__init__.py
from flask import Blueprint

admins = Blueprint('admins', __name__, template="templates")

from app.admins import routes

old_site/app/admins/routes.py
from flask import render_template, url_for, request, g, jsonify
from app.admins import admins

old_site/app/api/__init__.py
from flask import Blueprint

api = Blueprint('api', __name__)

from app.api import bids, website #, users, cities, payments, posts, website, categories, comments

old_site/app/comments/__init__.py
from flask import Blueprint

comments = Blueprint("comments", __name__, template_folder="templates")

from app.comments import routes

old_site/app/comments/routes.py
from flask import render_template, url_for
from app.comments import comments

@comments.route("/comments")
def comments():
    pass

old_site/app/posts/__init__.py
from flask import Blueprint

posts = Blueprint('posts', __name__, template_folder="templates")

from app.posts import routes

old_site/app/posts/routes.py
from flask import render_template, url_for, request, g
from app.posts import posts

@posts.route('/posts', methods=['GET'])
def posts():
    pass

old_site/app/users/__init__.py
from flask import Blueprint

users = Blueprint('users', __name__, template_folder='templates');

from app.users import routes

old_site/app/users/routes.py
from flask import render_template, jsonify, request, g, url_for
from flask_login import login_user, logout_user, login_required
from app.users import users

@users.route('/signin', methods=['GET'])
def signin():
    return render_template('signin.html')

@users.route('/signup', methods=['GET'])
def signup():
    return render_template('signup.html')

@users.route('/logout')
def logout():
    logout_user()

    return redirect(url_for('website.index'))

old_site/app/website/__init__.py
from flask import Blueprint

website = Blueprint('website', __name__, template_folder="templates")

from app.website import routes

old_site/app/website/routes.py
from flask import render_template, request, url_for, g, jsonify
from app.website import website

@website.route('/', methods=['GET'])
@website.route('/index', methods=['GET'])
def index():
    return render_template("index.html")

@website.route('/contact', methods=['GET'])
def contact():
    return render_template("contact.html")

@website.route('/how-it-works', methods=['GET'])
def howItWorks():
    return render_template('works.html')

@website.route('/about-us', methods=['GET'])
def aboutUs():
    return render_template('about.html')

@website.route('/terms-conditions', methods=['GET'])
def termsAndConditions():
    return render_template('termsConditions.html')

old_site/app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />

        <title>Contractors Bids {% block title %}{% endblock title %}</title>

        <link rel="icon" type="text/x-icon" href="{{ url_for('static', filename='img/website/favicon.ico') }}" />
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/libraries/semantic.min.css') }}" />
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/libraries/normalize.css') }}" />
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/custom/css/base.css') }}" />
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/custom/css/fonts.css') }}" />
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/custom/css/spaces.css') }}" />

        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>
        <!-- start header -->
        <header class="ui header segment background_color_header without_margin_main round_border remove_margins" id="header_body">
            <div class="ui container">
                <div class="ui grid">
                    <div class="five wide column">
                        <a href="{{ url_for('website.index') }}">
                            <img src="/static/img/website/logo.png" alt="logo" />
                        </a>
                    </div>
                    <div class="eleven wide column">
                        <a href="{{ url_for('users.signin') }}" class="ui white basic right floated button top_space_anchor_onefive">
                            Sign In
                        </a>
                        <a href="{{ url_for('users.signup') }}" class="ui white basic right floated button top_space_anchor_onefive">
                            Sign Up
                        </a>
                        <div class="clearfix"></div>
                    </div>
                </div>
                <div class="ui center aligned grid">
                    <div class="five wide column thin_font">
                        <a href="{{ url_for('website.howItWorks') }}" class="links_hover">
                            How it works?
                        </a>
                    </div>
                    <div class="five wide column thin_font">
                        <a href="{{ url_for('website.aboutUs') }}" class="links_hover">
                            About us
                        </a>
                    </div>
                    <div class="five wide column thin_font">
                        <a href="{{ url_for('website.contact') }}" class="links_hover">
                            Contact us
                        </a>
                    </div>
                    <div class="one wide column">&nbsp;</div>
                </div>
            </div>
        </header>
        <!-- end header -->

        <!-- start menu -->
        <div class="ui segment background_color_header round_border without_margin_main remove_margins">
            <div class="ui menu background_color_header">
                <div class="ui container">
                    <div class="ui simple dropdown item">
                        Projects
                        <i class="dropdown icon"></i>
                        <div class="menu">
                            <a href="">
                                Search a Project
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- end menu -->

        <!-- start body -->
        <div class="ui container">
            <div class="ui grid">
                {% block content %}
                {% endblock content %}
            </div>
        </div>
        <!-- end body -->

        <!-- start footer -->
        <div class="ui footer segment background_color_footer round_border">
            <div class="ui container">
                <div class="ui grid">
                    <div class="three column row">
                        <div class="four wide column space_padding_top_fifteen">
                            <a href="">
                                <img src="/static/img/website/facebook.png" width="40"
                                     height="40" alt="Twitter Social Network" />
                            </a>
                            <a href="">
                                <img src="/static/img/website/twitter.png" width="40"
                                     height="40" alt="Twitter Social Network" />
                            </a>
                        </div>
                        <div class="eight wide column">
                            <h2 class="gross_font color_font_white space_padding_top_fifteen">
                                "THE PROJECT THAT YOU WAS LOOKING FOR IS HERE"
                            </h2>
                        </div>
                        <div class="four wide column">&nbsp;</div>
                    </div>
                    <div class="three column row">
                        <div class="four wide column">&nbsp;</div>
                        <div class="eight wide column thin_font color_font_white">
                            <a href="{{ url_for('website.howItWorks') }}" class="links_hover">
                                How it works
                            </a> |
                            <a href="{{ url_for('website.aboutUs') }}" class="links_hover">
                                About us
                            </a> |
                            <a href="{{ url_for('website.contact') }}" class="links_hover">
                                Contact us
                            </a> |
                            <a href="{{ url_for('website.termsAndConditions') }}" class="links_hover">
                                Terms and Conditions
                            </a>
                        </div>
                        <div class="four wide column">&nbsp;</div>
                    </div>
                    <div class="one column row thin_font">
                        <h3 class="color_font_white">
                            © 2018 Copyright thecontractordepots.com
                        </h3>
                    </div>
                </div>
            </div>
        </div>
        <!-- end footer -->
    </body>
</html>